## Chi Square Test

The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables.

#### Here the data set taken from the tips restaurant (from kaggle) wheather is any relationship between the Gender and smoker

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("tips.csv")

In [3]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
data.shape

(244, 7)

null hypothesis H0:There is no relationship between 2 categorical variables  

alternative hypothesis Ha:There is a relationship between 2 categorical variables

In [11]:
data_table=pd.crosstab(data["sex"],data["smoker"])
print(data_table)  # here we did the cross tab to check the no.of smoker in male and female

smoker  No  Yes
sex            
Female  54   33
Male    97   60


In [12]:
data_table.values

array([[54, 33],
       [97, 60]], dtype=int64)

### Observed value

In [16]:
Observed_Values = data_table.values 
print("Observed Values :\n",Observed_Values)

Observed Values :
 [[54 33]
 [97 60]]


In [19]:
import scipy.stats as stats

In [20]:
val=stats.chi2_contingency(data_table)

In [21]:
val

(0.0,
 1.0,
 1,
 array([[53.84016393, 33.15983607],
        [97.15983607, 59.84016393]]))

In [22]:
val[3]

array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]])

In [28]:
Expected_Values=val[3]

In [29]:
Expected_Values

array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]])

In [30]:
no_of_rows=len(data_table.iloc[0:2,0])
no_of_columns=len(data_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [31]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [32]:
chi_square_statistic

0.001934818536627623

In [33]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [34]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Reject to fail H0,There is no relationship between 2 categorical variables")

Reject to fail H0,There is no relationship between 2 categorical variables


### So here in gender and smoking...there is no relationship in between